services:
  n8n:
    image: n8nio/n8n:2.16.1
    container_name: ${N8N_NAME}
    mem_limit: "3g"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
    networks:
      - proxy
    environment:
      - N8N_EDITOR_BASE_URL=https://${N8N_API_URL}
      - WEBHOOK_URL=https://${N8N_API_URL}
      - N8N_PORT=${N8N_API_PORT}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - n8n_data:/home/node/.n8n
    labels: 
      - "traefik.enable=true"
      - "traefik.http.routers.${N8N_NAME}.entrypoints=http"
      - "traefik.http.routers.${N8N_NAME}.rule=Host(`${N8N_API_URL}`)"
      - "traefik.http.routers.${N8N_NAME}-secure.entrypoints=https"
      - "traefik.http.routers.${N8N_NAME}-secure.rule=Host(`${N8N_API_URL}`)"
      - "traefik.http.routers.${N8N_NAME}-secure.tls=true"
      - "traefik.http.routers.${N8N_NAME}-secure.tls.certresolver=http"
      - "traefik.http.routers.${N8N_NAME}-secure.service=${N8N_NAME}"
      - "traefik.http.services.${N8N_NAME}.loadbalancer.server.port=${N8N_API_PORT}"
      - "traefik.docker.network=proxy"
      # middleware assignment
      - "traefik.http.routers.${N8N_NAME}.middlewares=https-redirect@file"

volumes:
  n8n_data:

networks:
  proxy:
    external: true